// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/632f527f65e5a614fe911511

### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "William",
  "lastName": "Rice",
  "email": "william@rice.com",
  "favoriteColor": "Red",
  "birthday": "12/30/2009"
}

// RENDER
### Get all contacts from Render
GET https://jessewilson341-a1.onrender.com/contacts

### Get contact by ID from Render
GET https://jessewilson341-a1.onrender.com/contacts/632f527f65e5a614fe911511

### Post new contact from Render
POST https://jessewilson341-a1.onrender.com/contacts
content-type: application/json

{
  "firstName": "William",
  "lastName": "Rice",
  "email": "william@rice.com",
  "favoriteColor": "Red",
  "birthday": "12/30/2009"
}